version: '3'
services: 
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      # download everything excepts the node modules  
      - /app/node_modules 
      # everything below the server directory goes to app 
      - ./server:/app
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes: 
      - /app/node_modules
      - ./client:/app
      